/**
 * The replay data source: the committed fixtures, served against a local
 * virtual clock as if they were arriving live.
 *
 * `frontend/src/fixtures/` holds a complete 640-virtual-second outage-and-
 * recovery run, generated by `make fixtures` from the same Pydantic models the
 * api serves. Replaying it drives the whole UI against a moving clock with no
 * backend process running at all.
 *
 * The fixtures are **dynamically imported**, so the half-megabyte of recorded
 * metrics is fetched only by someone who actually asks for the recording. Every
 * method on `DataSource` already returns a promise, so paying for that lazily
 * costs nothing above this file.
 *
 * Two honest limits, both surfaced in the UI rather than papered over:
 *
 * - The recording has `fair_drain_enabled: true`. It is the *after* picture, so
 *   the toggle is inert here -- flipping it cannot change a recording, and
 *   pretending otherwise would be the single most misleading thing this file
 *   could do.
 * - `decisions.json` is a 50-row *snapshot of the tail*, not a time series. The
 *   real endpoint is newest-first and replace-on-poll, so that is all it ever
 *   returned. The feed is therefore empty until the clock reaches the window it
 *   covers, which is correct rather than broken.
 */
import { phaseAt, toVirtualSeconds, VIRTUAL_EPOCH_ZERO_MS } from '../scenario'
import type { DataSource } from './source'
import type {
  ConsumerRead,
  DecisionRead,
  DecisionsPage,
  MetricsBucket,
  MetricsPage,
  ProcessRead,
  SimulationPatch,
  SimulationRead,
} from './types'

/**
 * The recorded run's id, duplicated here because `DataSource.simulationId` is
 * synchronous and the fixture that carries it is not. `loadRecording` throws if
 * the two ever disagree, so the duplication cannot rot silently.
 */
export const REPLAY_SIMULATION_ID = '11111111-2222-4333-8444-555555555555'

// ---------------------------------------------------------------------------
// The recording, indexed
// ---------------------------------------------------------------------------

interface Cumulative {
  delivered: number
  expired: number
  superseded: number
  failed: number
}

interface ConsumerTrack {
  /** Bucket boundaries, ascending. */
  ts: number[]
  /** Counters summed over every bucket up to and including `ts[i]`. */
  cum: Cumulative[]
  /** The raw bucket at `ts[i]`, for the gauges. */
  gauge: MetricsBucket[]
}

interface Recording {
  simulation: SimulationRead
  consumers: ConsumerRead[]
  buckets: MetricsBucket[]
  tracks: Map<number, ConsumerTrack>
  decisions: { at: number; decision: DecisionRead }[]
  processes: ProcessRead[]
  /** Where the recording stops: one past the last bucket it contains. */
  endS: number
}

let pending: Promise<Recording> | null = null

function loadRecording(): Promise<Recording> {
  pending ??= (async (): Promise<Recording> => {
    // The fixtures are generated from the frozen models, so these `unknown` hops
    // assert what `make fixtures-check` already enforces from the other side.
    // TypeScript widens JSON string literals to `string` and cannot see that
    // `state` is a `DeliveryState`.
    const [simulationJson, consumerJson, metricsJson, decisionsJson, processJson] =
      await Promise.all([
        import('../fixtures/simulation.json'),
        import('../fixtures/consumer.json'),
        import('../fixtures/metrics.json'),
        import('../fixtures/decisions.json'),
        import('../fixtures/process.json'),
      ])

    const simulation = simulationJson.default as unknown as SimulationRead
    if (simulation.id !== REPLAY_SIMULATION_ID) {
      throw new Error(
        `replay fixtures changed id: expected ${REPLAY_SIMULATION_ID}, got ${simulation.id}`,
      )
    }

    const buckets = [...(metricsJson.default as unknown as MetricsPage).buckets].sort(
      (a, b) => a.bucket_virtual_s - b.bucket_virtual_s || a.consumer_id - b.consumer_id,
    )

    return {
      simulation,
      consumers: consumerJson.default as unknown as ConsumerRead[],
      buckets,
      tracks: index(buckets),
      decisions: (decisionsJson.default as unknown as DecisionsPage).decisions
        .map((decision) => ({ at: toVirtualSeconds(decision.completed_at), decision }))
        .sort((a, b) => b.at - a.at),
      processes: processJson.default as unknown as ProcessRead[],
      endS: buckets.reduce((max, b) => Math.max(max, b.bucket_virtual_s), 0) + 1,
    }
  })()
  return pending
}

/**
 * Counters accumulate; gauges do not.
 *
 * The same distinction the conductor draws when it writes these buckets
 * (`app/conductor/metrics.py`): `attempts` and the four terminal columns are
 * *per-bucket counts*, so a consumer's card total at time `t` is their sum over
 * every bucket up to `t`; `backlog` / `ready` / `in_flight` are point-in-time
 * depths, so the card shows the latest one. Summing a gauge would draw a number
 * that only ever climbs -- plausible, monotonic, and wrong.
 */
function index(sorted: MetricsBucket[]): Map<number, ConsumerTrack> {
  const tracks = new Map<number, ConsumerTrack>()
  for (const bucket of sorted) {
    let track = tracks.get(bucket.consumer_id)
    if (!track) {
      track = { ts: [], cum: [], gauge: [] }
      tracks.set(bucket.consumer_id, track)
    }
    const previous = track.cum.at(-1) ?? { delivered: 0, expired: 0, superseded: 0, failed: 0 }
    track.ts.push(bucket.bucket_virtual_s)
    track.cum.push({
      delivered: previous.delivered + bucket.delivered,
      expired: previous.expired + bucket.expired,
      superseded: previous.superseded + bucket.superseded,
      failed: previous.failed + bucket.failed,
    })
    track.gauge.push(bucket)
  }
  return tracks
}

/** Rightmost index whose value is `<= t`, or -1. */
function lastIndexAtOrBefore(values: number[], t: number): number {
  let low = 0
  let high = values.length - 1
  let found = -1
  while (low <= high) {
    const mid = (low + high) >> 1
    if (values[mid] <= t) {
      found = mid
      low = mid + 1
    } else {
      high = mid - 1
    }
  }
  return found
}

// ---------------------------------------------------------------------------
// The source
// ---------------------------------------------------------------------------

export class ReplaySource implements DataSource {
  readonly kind = 'replay' as const
  readonly simulationId = REPLAY_SIMULATION_ID

  /** Virtual seconds at the last clock rewrite. */
  private anchorVirtualS = 0
  private anchorWallMs = Date.now()
  private speed = 20
  private status: SimulationRead['status'] = 'running'
  private fairDrainEnabled = true
  private outageOverride: boolean | null = null

  /**
   * Where the clock is now, clamping at the end of the recording.
   *
   * Reaching the end retires the run rather than looping. A recording that
   * silently restarted would read as a second outage; `done` is the same
   * terminal state the real simulation uses, so the control bar needs no
   * replay-specific case for it.
   */
  private read(recording: Recording): number {
    if (this.status !== 'running') return this.anchorVirtualS
    const elapsed = ((Date.now() - this.anchorWallMs) / 1000) * this.speed
    const t = this.anchorVirtualS + elapsed
    if (t >= recording.endS) {
      this.anchorVirtualS = recording.endS
      this.anchorWallMs = Date.now()
      this.status = 'done'
      return recording.endS
    }
    return t
  }

  async getSimulation(): Promise<SimulationRead> {
    const recording = await loadRecording()
    const t = this.read(recording)
    return {
      ...recording.simulation,
      status: this.status,
      speed_multiplier: this.speed,
      fair_drain_enabled: this.fairDrainEnabled,
      outage_override: this.outageOverride,
      virtual_now: new Date(VIRTUAL_EPOCH_ZERO_MS + t * 1000).toISOString(),
      virtual_now_s: t,
      phase: phaseAt(t, { outageOverride: this.outageOverride, done: this.status === 'done' }),
    }
  }

  async getConsumers(): Promise<ConsumerRead[]> {
    const recording = await loadRecording()
    const t = this.read(recording)
    return recording.consumers.map((consumer) => {
      const track = recording.tracks.get(consumer.id)
      const at = track ? lastIndexAtOrBefore(track.ts, t) : -1
      if (!track || at < 0) {
        return {
          ...consumer,
          backlog: 0,
          in_flight: 0,
          delivered: 0,
          expired: 0,
          superseded: 0,
          failed: 0,
          caught_up_after_s: null,
        }
      }
      return {
        ...consumer,
        backlog: track.gauge[at].backlog,
        in_flight: track.gauge[at].in_flight,
        ...track.cum[at],
        // Null on purpose: the live route returns null too, so the UI derives it
        // from the metrics buffer in both modes and there is one code path to
        // get wrong rather than two.
        caught_up_after_s: null,
      }
    })
  }

  async getMetrics(sinceBucket: number): Promise<MetricsPage> {
    const recording = await loadRecording()
    const t = this.read(recording)
    const buckets = recording.buckets.filter(
      (b) => b.bucket_virtual_s > sinceBucket && b.bucket_virtual_s <= t,
    )
    return {
      simulation_id: this.simulationId,
      buckets,
      next_since_bucket: buckets.at(-1)?.bucket_virtual_s ?? sinceBucket,
    }
  }

  async getDecisions(limit = 50): Promise<DecisionsPage> {
    const recording = await loadRecording()
    const t = this.read(recording)
    return {
      simulation_id: this.simulationId,
      decisions: recording.decisions
        .filter((d) => d.at <= t)
        .slice(0, limit)
        .map((d) => d.decision),
    }
  }

  async getProcesses(): Promise<ProcessRead[]> {
    return (await loadRecording()).processes
  }

  async patch(body: SimulationPatch): Promise<SimulationRead> {
    const recording = await loadRecording()
    // Rebase the anchor so virtual time is continuous across the change --
    // the same shape as the epoch rewrite in `app/core/clock.py`.
    const rewrite = () => {
      this.anchorVirtualS = this.read(recording)
      this.anchorWallMs = Date.now()
    }
    if (body.status !== undefined && body.status !== this.status) {
      rewrite()
      this.status = body.status
    }
    if (body.speed_multiplier !== undefined && body.speed_multiplier !== this.speed) {
      rewrite()
      this.speed = body.speed_multiplier
    }
    if (body.fair_drain_enabled !== undefined) this.fairDrainEnabled = body.fair_drain_enabled
    if (body.outage_override !== undefined) this.outageOverride = body.outage_override
    return this.getSimulation()
  }
}
