"""The whole schema, in one migration.

The design is settled enough that writing the model once is cheaper than
migrating to it five times.

Autogenerated from ``app.core.models`` and then read line by line -- partial
index predicates are the thing autogenerate most often gets subtly wrong, and
the three on ``delivery`` are the difference between the worker claim loop
being an index scan and being a sequential scan.

Revision ID: 0001
Revises:
Create Date: 2026-08-30
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "process",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("pid", sa.Integer(), nullable=False),
        sa.Column("started_at_wall", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_heartbeat_wall", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_leader", sa.Boolean(), nullable=False),
        sa.CheckConstraint("kind IN ('conductor', 'worker')", name=op.f("ck_process_kind")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_process")),
    )
    op.create_index("ix_process_liveness", "process", ["last_heartbeat_wall"], unique=False)
    op.create_table(
        "simulation",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at_wall", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("scenario_name", sa.String(length=64), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("virtual_epoch", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resumed_at_wall", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paused_at_virtual", sa.DateTime(timezone=True), nullable=True),
        sa.Column("speed_multiplier", sa.Float(), nullable=False),
        sa.Column("fair_drain_enabled", sa.Boolean(), nullable=False),
        sa.Column("global_attempts_per_s", sa.Float(), nullable=False),
        sa.Column("outage_override", sa.Boolean(), nullable=True),
        sa.CheckConstraint("status IN ('running', 'paused', 'done')", name=op.f("ck_simulation_status")),
        sa.CheckConstraint("speed_multiplier > 0", name=op.f("ck_simulation_speed_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simulation")),
    )
    op.create_table(
        "consumer",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("simulation_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("concurrency_cap", sa.Integer(), nullable=False),
        sa.Column("max_attempts_per_s", sa.Float(), nullable=False),
        sa.Column("sim_latency_s", sa.Float(), nullable=False),
        sa.Column("sim_jitter_s", sa.Float(), nullable=False),
        sa.Column("sim_failure_rate", sa.Float(), nullable=False),
        sa.Column("sim_down", sa.Boolean(), nullable=False),
        sa.CheckConstraint("concurrency_cap > 0", name=op.f("ck_consumer_concurrency_positive")),
        sa.CheckConstraint("max_attempts_per_s > 0", name=op.f("ck_consumer_rate_positive")),
        sa.CheckConstraint("weight > 0", name=op.f("ck_consumer_weight_positive")),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulation.id"],
            name=op.f("fk_consumer_simulation_id_simulation"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consumer")),
        sa.UniqueConstraint("simulation_id", "name", name="uq_consumer_simulation_id_name"),
    )
    op.create_index(op.f("ix_consumer_simulation_id"), "consumer", ["simulation_id"], unique=False)
    op.create_table(
        "event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("simulation_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("entity_key", sa.String(length=128), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulation.id"],
            name=op.f("fk_event_simulation_id_simulation"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event")),
    )
    op.create_table(
        "delivery",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("simulation_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("consumer_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("entity_key", sa.String(length=128), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("leased_by", sa.UUID(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terminal_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state IN ('pending', 'ready', 'in_flight', 'delivered', 'expired', 'superseded', 'failed')",
            name=op.f("ck_delivery_state"),
        ),
        sa.ForeignKeyConstraint(
            ["consumer_id"],
            ["consumer.id"],
            name=op.f("fk_delivery_consumer_id_consumer"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["event.id"], name=op.f("fk_delivery_event_id_event"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulation.id"],
            name=op.f("fk_delivery_simulation_id_simulation"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery")),
    )
    op.create_index(
        "ix_delivery_coalesce",
        "delivery",
        ["consumer_id", "event_type", "entity_key"],
        unique=False,
        postgresql_where=sa.text("state IN ('pending', 'ready')"),
    )
    op.create_index("ix_delivery_completed", "delivery", ["simulation_id", "completed_at"], unique=False)
    op.create_index(
        "ix_delivery_pending",
        "delivery",
        ["simulation_id", "consumer_id", "next_attempt_at"],
        unique=False,
        postgresql_where=sa.text("state = 'pending'"),
    )
    op.create_index(
        "ix_delivery_ready",
        "delivery",
        ["simulation_id", "ready_at"],
        unique=False,
        postgresql_where=sa.text("state = 'ready'"),
    )
    op.create_table(
        "delivery_policy",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("simulation_id", sa.UUID(), nullable=False),
        sa.Column("consumer_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("max_staleness_s", sa.Float(), nullable=True),
        sa.Column("coalesce", sa.Text(), nullable=False),
        sa.CheckConstraint("coalesce IN ('none', 'latest_by_key')", name=op.f("ck_delivery_policy_coalesce")),
        sa.CheckConstraint(
            "max_staleness_s IS NULL OR max_staleness_s > 0",
            name=op.f("ck_delivery_policy_staleness_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["consumer_id"],
            ["consumer.id"],
            name=op.f("fk_delivery_policy_consumer_id_consumer"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulation.id"],
            name=op.f("fk_delivery_policy_simulation_id_simulation"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_policy")),
        sa.UniqueConstraint("consumer_id", "event_type", name="uq_delivery_policy_consumer_id_event_type"),
    )
    op.create_table(
        "metrics_snapshot",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("simulation_id", sa.UUID(), nullable=False),
        sa.Column("consumer_id", sa.BigInteger(), nullable=False),
        sa.Column("bucket_virtual_s", sa.Integer(), nullable=False),
        sa.Column("backlog", sa.Integer(), nullable=False),
        sa.Column("ready", sa.Integer(), nullable=False),
        sa.Column("in_flight", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("delivered", sa.Integer(), nullable=False),
        sa.Column("expired", sa.Integer(), nullable=False),
        sa.Column("superseded", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["consumer_id"],
            ["consumer.id"],
            name=op.f("fk_metrics_snapshot_consumer_id_consumer"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulation.id"],
            name=op.f("fk_metrics_snapshot_simulation_id_simulation"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metrics_snapshot")),
        sa.UniqueConstraint(
            "simulation_id",
            "consumer_id",
            "bucket_virtual_s",
            name="uq_metrics_snapshot_simulation_id_consumer_id_bucket_virtual_s",
        ),
    )
    op.create_index(
        "ix_metrics_snapshot_cursor", "metrics_snapshot", ["simulation_id", "bucket_virtual_s"], unique=False
    )
    op.create_table(
        "subscription",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("simulation_id", sa.UUID(), nullable=False),
        sa.Column("consumer_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["consumer_id"],
            ["consumer.id"],
            name=op.f("fk_subscription_consumer_id_consumer"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulation.id"],
            name=op.f("fk_subscription_simulation_id_simulation"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription")),
        sa.UniqueConstraint("consumer_id", "event_type", name="uq_subscription_consumer_id_event_type"),
    )
    op.create_index("ix_subscription_fanout", "subscription", ["simulation_id", "event_type"], unique=False)
    op.create_table(
        "attempt",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("simulation_id", sa.UUID(), nullable=False),
        sa.Column("delivery_id", sa.BigInteger(), nullable=False),
        sa.Column("consumer_id", sa.BigInteger(), nullable=False),
        sa.Column("worker_id", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "outcome IS NULL OR outcome IN ('ok', '5xx', 'timeout')", name=op.f("ck_attempt_outcome")
        ),
        sa.ForeignKeyConstraint(
            ["consumer_id"], ["consumer.id"], name=op.f("fk_attempt_consumer_id_consumer"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["delivery_id"], ["delivery.id"], name=op.f("fk_attempt_delivery_id_delivery"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulation.id"],
            name=op.f("fk_attempt_simulation_id_simulation"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempt")),
    )
    op.create_index(op.f("ix_attempt_delivery_id"), "attempt", ["delivery_id"], unique=False)
    op.create_index("ix_attempt_window", "attempt", ["consumer_id", "started_at"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_attempt_window", table_name="attempt")
    op.drop_index(op.f("ix_attempt_delivery_id"), table_name="attempt")
    op.drop_table("attempt")
    op.drop_index("ix_subscription_fanout", table_name="subscription")
    op.drop_table("subscription")
    op.drop_index("ix_metrics_snapshot_cursor", table_name="metrics_snapshot")
    op.drop_table("metrics_snapshot")
    op.drop_table("delivery_policy")
    op.drop_index("ix_delivery_ready", table_name="delivery", postgresql_where=sa.text("state = 'ready'"))
    op.drop_index("ix_delivery_pending", table_name="delivery", postgresql_where=sa.text("state = 'pending'"))
    op.drop_index("ix_delivery_completed", table_name="delivery")
    op.drop_index(
        "ix_delivery_coalesce",
        table_name="delivery",
        postgresql_where=sa.text("state IN ('pending', 'ready')"),
    )
    op.drop_table("delivery")
    op.drop_table("event")
    op.drop_index(op.f("ix_consumer_simulation_id"), table_name="consumer")
    op.drop_table("consumer")
    op.drop_table("simulation")
    op.drop_index("ix_process_liveness", table_name="process")
    op.drop_table("process")
